version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379" # Change host port to avoid conflicts
    restart: unless-stopped

  app:
    build: .
    container_name: python_app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./model:/app/model
    restart: unless-stopped